#!/usr/bin/env python3
"""Generate a simple draft for testing approval gates."""
import os
import json
from datetime import datetime

output_path = os.environ.get('PIPELINE_OUTPUT', '/tmp/draft.md')
os.makedirs(os.path.dirname(output_path), exist_ok=True)

draft = f"""# Draft Report — {datetime.now().strftime('%Y-%m-%d %H:%M')}

## Summary
This is a test draft generated by the gate-test pipeline.
It exercises the approval and prompt step types.

## Key Points
- Approval gates pause the pipeline for human review
- Prompt steps ask questions and pass answers downstream
- Both support configurable timeouts

## Status
Ready for review.
"""

with open(output_path, 'w') as f:
    f.write(draft)

print(json.dumps({"status": "ok", "output": output_path}))
