#!/usr/bin/env python3
"""Format step: Read enhanced JSON and produce a markdown file."""

import json
import os
import sys
from datetime import date


def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("PIPELINE_INPUT", "")
    output_file = os.environ.get("PIPELINE_OUTPUT", "/tmp/daily-quote.md")

    if not input_file or not os.path.exists(input_file):
        print(json.dumps({"error": f"Input file not found: {input_file}"}))
        sys.exit(1)

    with open(input_file) as f:
        data = json.load(f)

    quote = data.get("quote", "No quote")
    author = data.get("author", "Unknown")
    commentary = data.get("commentary", "No commentary available.")

    today = date.today().isoformat()

    md = f"""---
type: daily-quote
date: {today}
author: {author}
---

# Daily Quote — {today}

> "{quote}"
> — **{author}**

## Commentary

{commentary}

---
*Generated by Soul Hub Pipeline: daily-quote*
"""

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)

    with open(output_file, "w") as f:
        f.write(md)

    print(f"Formatted quote to {output_file}")
    print(json.dumps({"status": "done", "output": output_file}))


if __name__ == "__main__":
    main()
